project_id = "bujbbvcexwscnhgrcezn"

[functions.action-counsellor]
verify_jwt = true

[functions.task-generator]
verify_jwt = true

[functions.scheduler]
verify_jwt = true

[functions.workflow-processor]
verify_jwt = true

[functions.ai-task-breakdown]
verify_jwt = false

[functions.ai-daily-plan]
verify_jwt = true

[functions.ai-task-sorter]
verify_jwt = true

[functions.ai-brain-dump]
verify_jwt = true

[functions.ai-xp-calculator]
verify_jwt = true
